const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');
const http = require('node:http');
const root = path.resolve(__dirname, '..');
fs.mkdirSync(path.join(root, 'test-results'), {recursive:true});
const checks = [];
const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log(`PASS ${name}`); };
const server = http.createServer((req, res) => {
  const pathname = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
  const file = path.resolve(root, '.' + (pathname === '/' ? '/index.html' : pathname));
  if (!file.startsWith(root + path.sep)) { res.writeHead(403); return res.end(); }
  fs.readFile(file, (error, data) => {
    if (error) { res.writeHead(404); return res.end(); }
    const types = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
    res.setHeader('Content-Type', types[path.extname(file)] || 'application/octet-stream');
    res.end(data);
  });
});
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({channel:process.env.BROWSER_CHANNEL || 'msedge',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1100}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(url);
    check('初始顯示八首歌曲', await page.locator('.song-item').count() === 8);
    await page.screenshot({path:path.join(root,'test-results','desktop.png'),fullPage:true});
    await page.locator('#search').fill('芙莉蓮');
    check('中文原作搜尋', await page.locator('.song-item').count() === 1);
    await page.locator('.song-item').click();
    await page.waitForFunction(() => document.querySelector('#song-title').textContent === '勇者');
    check('歌曲與原作資料同步', await page.locator('#story-title').textContent() === '奏送');
    await page.locator('.skip-link').focus();
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => document.activeElement.id === 'main');
    check('跳至內容保留歌曲路由', await page.locator('#song-title').textContent() === '勇者' && page.url().endsWith('#song/yuusha'));
    await page.locator('#favorite').click();
    await page.reload();
    check('收藏重新整理後保留', await page.locator('#favorite').getAttribute('aria-pressed') === 'true');
    await page.locator('[data-filter=favorites]').click();
    check('收藏分類', await page.locator('.song-item').count() === 1);
    await page.locator('#favorite').click();
    check('移除收藏後空狀態', await page.locator('#empty-list').isVisible());
    await page.locator('#reset-filters').click();
    await page.locator('#search').fill('no-such-song');
    check('搜尋無結果狀態', await page.locator('#empty-list').isVisible());
    await page.locator('#reset-filters').click();
    await page.locator('[data-panel=lyrics]').click();
    check('歌詞未匯入時不冒充正版內容', await page.locator('.lyrics-empty').isVisible());
    await page.locator('#open-import').click();
    await page.locator('#lyrics-input').fill('invalid');
    await page.locator('button[type=submit]').click();
    check('不合法 JSON 顯示錯誤', (await page.locator('#import-error').textContent()).includes('JSON'));
    await page.locator('#load-example').click();
    await page.locator('button[type=submit]').click();
    check('示範內容標示非歌詞', (await page.locator('#lyrics-origin').textContent()).includes('並非 YOASOBI'));
    check('雙語顯示', await page.locator('.lyric-ja').count() === 2 && await page.locator('.lyric-zh').count() === 2);
    await page.locator('[data-language=ja]').click();
    check('只看日文', await page.locator('.lyric-ja').count() === 2 && await page.locator('.lyric-zh').count() === 0);
    await page.locator('[data-language=zh]').click();
    check('只看中文', await page.locator('.lyric-ja').count() === 0 && await page.locator('.lyric-zh').count() === 2);
    await page.reload();
    await page.locator('[data-panel=lyrics]').click();
    check('匯入內容重新整理後保留', await page.locator('.lyric-row').count() === 2);
    await page.locator('#open-import').click();
    await page.keyboard.press('Escape');
    check('Escape 關閉且焦點返回', !(await page.locator('#import-dialog').isVisible()) && await page.locator('#open-import').evaluate(node => node === document.activeElement));
    await page.locator('#open-import').click();
    const payload = JSON.stringify([{ja:'<img src=x onerror=alert(1)>',zh:'安全純文字'}]);
    await page.locator('#lyrics-file').setInputFiles({name:'sample.json',mimeType:'application/json',buffer:Buffer.from(payload)});
    await page.waitForFunction(value => document.querySelector('#lyrics-input').value === value, payload);
    await page.locator('button[type=submit]').click();
    check('檔案匯入與 HTML 注入防護', await page.locator('#lyrics-content img').count() === 0 && (await page.locator('.lyric-ja').textContent()).includes('<img'));
    await page.locator('#delete-lyrics').click();
    check('清除匯入內容', await page.locator('.lyrics-empty').isVisible());
    await page.locator('button[data-theme=wine]').click();
    await page.reload();
    check('主題重新整理後保留', await page.locator('body').getAttribute('data-theme') === 'wine');
    await page.locator('.artist-link').click();
    await page.locator('#artist-page').waitFor({state:'visible'});
    check('ikura 基本資料', await page.locator('#artist-page').isVisible() && (await page.locator('#artist-page').textContent()).includes('2000 年 9 月 25 日'));
    await page.screenshot({path:path.join(root,'test-results','artist.png'),fullPage:true});
    await page.goto(url + '/#song/yoru');
    await page.locator('button[data-theme=forest]').click();
    for (const width of [360,390,768,1024,1440]) {
      await page.setViewportSize({width,height:900});
      check(`${width}px 無水平溢出`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    }
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(root,'test-results','mobile.png'),fullPage:true});
    await page.locator('[data-panel=lyrics]').click();
    await page.locator('#open-import').click();
    await page.screenshot({path:path.join(root,'test-results','mobile-dialog.png'),fullPage:true});
    await page.keyboard.press('Escape');
    check('沒有 JavaScript 執行錯誤', errors.length === 0);
    const denied = await browser.newContext();
    await denied.addInitScript(() => Object.defineProperty(window, 'localStorage', {get(){throw Error('denied')}}));
    const deniedPage = await denied.newPage();
    await deniedPage.goto(url);
    await deniedPage.locator('#favorite').click();
    check('儲存權限拒絕仍可操作並提示', (await deniedPage.locator('#toast').textContent()).includes('無法儲存') && await deniedPage.locator('#favorite').getAttribute('aria-pressed') === 'true');
    await denied.close();
    const corrupt = await browser.newContext();
    await corrupt.addInitScript(() => {localStorage.setItem('yoru.favorites','{}');localStorage.setItem('yoru.lyrics','{"yoru":{"rows":[null]}}');});
    const corruptPage = await corrupt.newPage();
    await corruptPage.goto(url);
    await corruptPage.locator('[data-panel=lyrics]').click();
    check('損壞儲存資料可恢復', await corruptPage.locator('.lyrics-empty').isVisible());
    check('損壞儲存資料顯示提示', (await corruptPage.locator('#toast').textContent()).includes('無法讀取'));
    await corrupt.close();
    const local = await browser.newPage();
    await local.goto(pathToFileURL(path.join(root,'index.html')).href);
    check('直接 file:// 開啟可用', await local.locator('.song-item').count() === 8);
    console.log(`\n${checks.length} browser checks passed.`);
    fs.writeFileSync(path.join(root,'test-results','browser-report.json'),JSON.stringify({date:new Date().toISOString(),checks,errors},null,2));
  } finally { await browser.close(); server.close(); }
})().catch(error => {console.error(error);server.close();process.exitCode=1;});
